package com.example.myapplication;

import android.os.Bundle;
import android.util.Log;
import android.webkit.WebView;
import android.webkit.WebViewClient;

import androidx.appcompat.app.AppCompatActivity;

public class MainActivity extends AppCompatActivity {

    private static final String TAG = "MainActivity";
    private WebView mWebView;
    private String html = "<div class=\"contents\"> \n" +
            " <p class=\"0\" style=\"text-align: center; text-indent: -59.7pt; margin-left: 80px;\"><span style=\"line-height: 130%;\"><span style=\"-ms-word-break: keep-all;\"><span lang=\"EN-US\" style=\"font-size: 15pt;\"><span style=\"letter-spacing: 0pt;\"><span style=\"font-family: 휴먼명조;\">(</span></span></span><span style=\"font-size: 15pt;\"><span style=\"font-family: 휴먼명조;\">유</span></span><span lang=\"EN-US\" style=\"font-size: 15pt;\"><span style=\"letter-spacing: 0pt;\"><span style=\"font-family: 휴먼명조;\">)</span></span></span><span style=\"font-size: 15pt;\"><span style=\"font-family: HY헤드라인M;\">성원엘리베이터</span></span><span lang=\"EN-US\" style=\"font-size: 15pt;\"><span style=\"letter-spacing: 0pt;\"><span style=\"font-family: HY헤드라인M;\">, </span></span></span><span style=\"font-size: 15pt;\"><span style=\"font-family: HY헤드라인M;\">공주대 발전기금 </span></span><span lang=\"EN-US\" style=\"font-size: 15pt;\"><span style=\"letter-spacing: 0pt;\"><span style=\"font-family: HY헤드라인M;\">1,000</span></span></span><span style=\"font-size: 15pt;\"><span style=\"font-family: HY헤드라인M;\">만원 쾌척</span></span></span></span></p> \n" +
            " <p class=\"0\" style=\"text-align: center; text-indent: -59.7pt; margin-left: 80px;\"><span style=\"line-height: 130%;\"><span style=\"-ms-word-break: keep-all;\"><span lang=\"EN-US\" style=\"font-size: 13pt;\"><span style=\"letter-spacing: 0pt;\"><span style=\"font-family: 나눔고딕 ExtraBold;\">- </span></span></span><span style=\"font-size: 13pt;\"><span style=\"font-family: 나눔고딕 ExtraBold;\">세종캠퍼스 학교사랑 </span></span><span lang=\"EN-US\" style=\"font-size: 13pt;\"><span style=\"letter-spacing: 0pt;\"><span style=\"font-family: 나눔고딕 ExtraBold;\">1</span></span></span><span style=\"font-size: 13pt;\"><span style=\"font-family: 나눔고딕 ExtraBold;\">평 갖기 캠페인 동참 </span></span><span lang=\"EN-US\" style=\"font-size: 13pt;\"><span style=\"letter-spacing: 0pt;\"><span style=\"font-family: 나눔고딕 ExtraBold;\">-</span></span></span></span></span></p> \n" +
            " <p class=\"0\" style=\"text-align: center; text-indent: -59.7pt; margin-left: 80px;\"><span style=\"font-size: 13pt;\"><span style=\"line-height: 130%;\"><span style=\"-ms-word-break: keep-all;\">&nbsp; </span></span></span></p> \n" +
            " <p class=\"0\"><span style=\"line-height: 180%;\"><span style=\"font-size: 12pt;\"><span style=\"font-family: 휴먼명조;\"><img alt=\"발전1\" src=\"file:///android_asset/images/upload/발407a2246ddc44039a41aafa86fad55521.jpg\" style=\"width: 697px; height: 370px;\">국립 공주대학교</span></span><span lang=\"EN-US\" style=\"font-size: 12pt;\"><span style=\"letter-spacing: 0pt;\"><span style=\"font-family: 휴먼명조;\">(</span></span></span><span style=\"font-size: 12pt;\"><span style=\"font-family: 휴먼명조;\">총장 원성수</span></span><span lang=\"EN-US\" style=\"font-size: 12pt;\"><span style=\"letter-spacing: 0pt;\"><span style=\"font-family: 휴먼명조;\">)</span></span></span><span style=\"font-size: 12pt;\"><span style=\"font-family: 휴먼명조;\">는 </span></span><span lang=\"EN-US\" style=\"font-size: 12pt;\"><span style=\"letter-spacing: 0pt;\"><span style=\"font-family: 휴먼명조;\">25</span></span></span><span style=\"font-size: 12pt;\"><span style=\"font-family: 휴먼명조;\">일 대학본부 총장 접견실에서 </span></span><span lang=\"EN-US\" style=\"font-size: 12pt;\"><span style=\"letter-spacing: 0pt;\"><span style=\"font-family: 휴먼명조;\">(</span></span></span><span style=\"font-size: 12pt;\"><span style=\"font-family: 휴먼명조;\">유</span></span><span lang=\"EN-US\" style=\"font-size: 12pt;\"><span style=\"letter-spacing: 0pt;\"><span style=\"font-family: 휴먼명조;\">)</span></span></span><span style=\"font-size: 12pt;\"><span style=\"font-family: 휴먼명조;\">성원엘리베이터 양해정</span></span><span style=\"font-size: 12pt;\"><span style=\"letter-spacing: 0pt;\"><span style=\"font-family: 휴먼명조;\">？</span></span></span><span style=\"font-size: 12pt;\"><span style=\"font-family: 휴먼명조;\">남미현 부부 공동대표으로 부터 대학 발전기금 </span></span><span lang=\"EN-US\" style=\"font-size: 12pt;\"><span style=\"letter-spacing: 0pt;\"><span style=\"font-family: 휴먼명조;\">1,000</span></span></span><span style=\"font-size: 12pt;\"><span style=\"font-family: 휴먼명조;\">만원을 받았다</span></span><span lang=\"EN-US\" style=\"font-size: 12pt;\"><span style=\"letter-spacing: 0pt;\"><span style=\"font-family: 휴먼명조;\">.(</span></span></span><span style=\"font-size: 12pt;\"><span style=\"font-family: 휴먼명조;\">사진</span></span><span lang=\"EN-US\" style=\"font-size: 12pt;\"><span style=\"letter-spacing: 0pt;\"><span style=\"font-family: 휴먼명조;\">)</span></span></span></span></p> \n" +
            " <p class=\"0\" style=\"text-indent: -20.1pt; margin-left: 27px;\"><span style=\"font-size: 12pt;\"><span style=\"line-height: 180%;\">&nbsp; </span></span></p> \n" +
            " <p class=\"0\"><span style=\"line-height: 180%;\"><span lang=\"EN-US\" style=\"font-size: 12pt;\"><span style=\"letter-spacing: 0pt;\"><span style=\"font-family: 휴먼명조;\">(</span></span></span><span style=\"font-size: 12pt;\"><span style=\"font-family: 휴먼명조;\">유</span></span><span lang=\"EN-US\" style=\"font-size: 12pt;\"><span style=\"letter-spacing: 0pt;\"><span style=\"font-family: 휴먼명조;\">)</span></span></span><span style=\"font-size: 12pt;\"><span style=\"font-family: 휴먼명조;\">성원엘리베이터 양해정</span></span><span style=\"font-size: 12pt;\"><span style=\"letter-spacing: 0pt;\"><span style=\"font-family: 휴먼명조;\">？</span></span></span><span style=\"font-size: 12pt;\"><span style=\"font-family: 휴먼명조;\">남미현 공동대표는</span></span> <span style=\"font-size: 12pt;\"><span style=\"font-family: 휴먼명조;\">공주대학교를 방문하여 세종캠퍼스 입주 선정을 축하하고</span></span><span lang=\"EN-US\" style=\"font-size: 12pt;\"><span style=\"letter-spacing: 0pt;\"><span style=\"font-family: 휴먼명조;\">, </span></span></span><span style=\"font-size: 12pt;\"><span style=\"font-family: 휴먼명조;\">캠퍼스 부지매입에 써 달라며 공주대 원성수 총장에게 발전기금을 전달했다</span></span><span lang=\"EN-US\" style=\"font-size: 12pt;\"><span style=\"letter-spacing: 0pt;\"><span style=\"font-family: 휴먼명조;\">.</span></span></span></span></p> \n" +
            " <p class=\"0\" style=\"text-indent: -18.6pt; margin-left: 25px;\"><span style=\"font-size: 12pt;\"><span style=\"line-height: 180%;\">&nbsp; </span></span></p> \n" +
            " <p class=\"0\"><span style=\"line-height: 180%;\"><span style=\"font-size: 12pt;\"><span style=\"font-family: 휴먼명조;\">이날 기탁식 행사는 코로나</span></span><span lang=\"EN-US\" style=\"font-size: 12pt;\"><span style=\"letter-spacing: 0pt;\"><span style=\"font-family: 휴먼명조;\">19 </span></span></span><span style=\"font-size: 12pt;\"><span style=\"font-family: 휴먼명조;\">방역수칙에 준수하여 원성수 총장을 비롯한 보직교수</span></span><span lang=\"EN-US\" style=\"font-size: 12pt;\"><span style=\"letter-spacing: 0pt;\"><span style=\"font-family: 휴먼명조;\">, </span></span></span><span style=\"font-size: 12pt;\"><span style=\"font-family: 휴먼명조;\">조병고 시설과장</span></span><span lang=\"EN-US\" style=\"font-size: 12pt;\"><span style=\"letter-spacing: 0pt;\"><span style=\"font-family: 휴먼명조;\">, </span></span></span><span lang=\"EN-US\" style=\"font-size: 12pt;\"><span style=\"letter-spacing: 0pt;\"><span style=\"font-family: 휴먼명조;\">(</span></span></span><span style=\"font-size: 12pt;\"><span style=\"font-family: 휴먼명조;\">유</span></span><span lang=\"EN-US\" style=\"font-size: 12pt;\"><span style=\"letter-spacing: 0pt;\"><span style=\"font-family: 휴먼명조;\">)</span></span></span><span style=\"font-size: 12pt;\"><span style=\"font-family: 휴먼명조;\">성원엘리베이터 양해정</span></span><span style=\"font-size: 12pt;\"><span style=\"letter-spacing: 0pt;\"><span style=\"font-family: 휴먼명조;\">？</span></span></span><span style=\"font-size: 12pt;\"><span style=\"font-family: 휴먼명조;\">남미현 부부 등</span></span> <span style=\"font-size: 12pt;\"><span style=\"font-family: 휴먼명조;\">관계자가 참석한 가운데 진행됐다</span></span><span lang=\"EN-US\" style=\"font-size: 12pt;\"><span style=\"letter-spacing: 0pt;\"><span style=\"font-family: 휴먼명조;\">.</span></span></span></span></p> \n" +
            " <p class=\"0\" style=\"text-indent: -19.6pt; margin-left: 26px;\"><span style=\"font-size: 12pt;\"><span style=\"line-height: 180%;\">&nbsp; </span></span></p> \n" +
            " <p class=\"0\"><span style=\"line-height: 180%;\"><span style=\"font-size: 12pt;\"><span style=\"font-family: 휴먼명조;\">부부 공동대표 양해정</span></span><span style=\"font-size: 12pt;\"><span style=\"letter-spacing: 0pt;\"><span style=\"font-family: 휴먼명조;\">？</span></span></span><span style=\"font-size: 12pt;\"><span style=\"font-family: 휴먼명조;\">남미현씨는 </span></span><span lang=\"EN-US\" style=\"font-size: 12pt;\"><span style=\"letter-spacing: 0pt;\"><span style=\"font-family: 휴먼명조;\">“</span></span></span><span style=\"font-size: 12pt;\"><span style=\"font-family: 휴먼명조;\">공주대가 추진하고 있는 세종캠퍼스 학교 사랑</span></span><span lang=\"EN-US\" style=\"font-size: 12pt;\"><span style=\"letter-spacing: 0pt;\"><span style=\"font-family: 휴먼명조;\">1</span></span></span><span style=\"font-size: 12pt;\"><span style=\"font-family: 휴먼명조;\">평 갖기 캠페인 취지를 잘 알고 있다</span></span><span lang=\"EN-US\" style=\"font-size: 12pt;\"><span style=\"letter-spacing: 0pt;\"><span style=\"font-family: 휴먼명조;\">”</span></span></span><span style=\"font-size: 12pt;\"><span style=\"font-family: 휴먼명조;\">라며</span></span><span lang=\"EN-US\" style=\"font-size: 12pt;\"><span style=\"letter-spacing: 0pt;\"><span style=\"font-family: 휴먼명조;\">“</span></span></span><span style=\"font-size: 12pt;\"><span style=\"font-family: 휴먼명조;\">인재 양성을 선도하는 대학으로 우뚝 성장하여 세계로 뻗어가는 대학으로 발전하길 기원 한다</span></span><span lang=\"EN-US\" style=\"font-size: 12pt;\"><span style=\"letter-spacing: 0pt;\"><span style=\"font-family: 휴먼명조;\">”</span></span></span><span style=\"font-size: 12pt;\"><span style=\"font-family: 휴먼명조;\">라고 덧붙였다</span></span><span lang=\"EN-US\" style=\"font-size: 12pt;\"><span style=\"letter-spacing: 0pt;\"><span style=\"font-family: 휴먼명조;\">.</span></span></span></span></p> \n" +
            " <p class=\"0\" style=\"text-indent: -18.2pt; margin-left: 24px;\"><span style=\"font-size: 12pt;\"><span style=\"line-height: 180%;\">&nbsp; </span></span></p> \n" +
            " <p class=\"0\"><span style=\"line-height: 180%;\"><span style=\"font-size: 12pt;\"><span style=\"font-family: 휴먼명조;\"><img alt=\"발전2\" src=\"https://www.hanju.ac.kr/upload/발eef2ba0b96854726b076b5ed2bb464711.jpg\" style=\"width: 690px; height: 389px;\">원성수 총장은</span></span><span lang=\"EN-US\" style=\"font-size: 12pt;\"><span style=\"letter-spacing: 0pt;\"><span style=\"font-family: 휴먼명조;\">“</span></span></span><span style=\"font-size: 12pt;\"><span style=\"font-family: 휴먼명조;\">어려운 경제적 여건 속에서도 공주대 발전 사업에 적극적으로 동참하고 성원해 주셔서 감사드린다</span></span><span lang=\"EN-US\" style=\"font-size: 12pt;\"><span style=\"letter-spacing: 0pt;\"><span style=\"font-family: 휴먼명조;\">.”</span></span></span><span style=\"font-size: 12pt;\"><span style=\"font-family: 휴먼명조;\">라며</span></span><span lang=\"EN-US\" style=\"font-size: 12pt;\"><span style=\"letter-spacing: 0pt;\"><span style=\"font-family: 휴먼명조;\">“</span></span></span><span style=\"font-size: 12pt;\"><span style=\"font-family: 휴먼명조;\">지역사회와 함께 공주대가 충남세종의 대표 국립대학교로 성장 발전시키는데 최선을 다하겠다</span></span><span lang=\"EN-US\" style=\"font-size: 12pt;\"><span style=\"letter-spacing: 0pt;\"><span style=\"font-family: 휴먼명조;\">”</span></span></span><span style=\"font-size: 12pt;\"><span style=\"font-family: 휴먼명조;\">고 밝혔다</span></span><span lang=\"EN-US\" style=\"font-size: 12pt;\"><span style=\"letter-spacing: 0pt;\"><span style=\"font-family: 휴먼명조;\">.</span></span></span></span></p> \n" +
            " <p class=\"0\" style=\"text-indent: -18.1pt; margin-left: 24px;\"><span style=\"font-size: 12pt;\"><span style=\"line-height: 180%;\">&nbsp; </span></span></p> \n" +
            " <p class=\"0\"><span style=\"line-height: 180%;\"><span style=\"font-size: 12pt;\"><span style=\"font-family: 휴먼명조;\">한편</span></span><span lang=\"EN-US\" style=\"font-size: 12pt;\"><span style=\"letter-spacing: 0pt;\"><span style=\"font-family: 휴먼명조;\">, </span></span></span><span style=\"font-size: 12pt;\"><span style=\"font-family: 휴먼명조;\">공주대학교 세종캠퍼스</span></span><span lang=\"EN-US\" style=\"font-size: 12pt;\"><span style=\"letter-spacing: 0pt;\"><span style=\"font-family: 휴먼명조;\">‘</span></span></span><span style=\"font-size: 12pt;\"><span style=\"font-family: 휴먼명조;\">학교사랑 </span></span><span lang=\"EN-US\" style=\"font-size: 12pt;\"><span style=\"letter-spacing: 0pt;\"><span style=\"font-family: 휴먼명조;\">1</span></span></span><span style=\"font-size: 12pt;\"><span style=\"font-family: 휴먼명조;\">평 갖기</span></span><span lang=\"EN-US\" style=\"font-size: 12pt;\"><span style=\"letter-spacing: 0pt;\"><span style=\"font-family: 휴먼명조;\">’</span></span></span><span style=\"font-size: 12pt;\"><span style=\"font-family: 휴먼명조;\">캠페인은 대학 구성원 및 동문</span></span><span lang=\"EN-US\" style=\"font-size: 12pt;\"><span style=\"letter-spacing: 0pt;\"><span style=\"font-family: 휴먼명조;\">, </span></span></span><span style=\"font-size: 12pt;\"><span style=\"font-family: 휴먼명조;\">학생</span></span><span lang=\"EN-US\" style=\"font-size: 12pt;\"><span style=\"letter-spacing: 0pt;\"><span style=\"font-family: 휴먼명조;\">, </span></span></span><span style=\"font-size: 12pt;\"><span style=\"font-family: 휴먼명조;\">일반인들을 대상으로 진행하고 있으며</span></span><span lang=\"EN-US\" style=\"font-size: 12pt;\"><span style=\"letter-spacing: 0pt;\"><span style=\"font-family: 휴먼명조;\">, </span></span></span><span style=\"font-size: 12pt;\"><span style=\"font-family: 휴먼명조;\">공주대 발전기금 홈페이지</span></span><span lang=\"EN-US\" style=\"font-size: 12pt;\"><span style=\"letter-spacing: 0pt;\"><span style=\"font-family: 휴먼명조;\">(https://fund.kongju.ac.kr)</span></span></span><span style=\"font-size: 12pt;\"><span style=\"font-family: 휴먼명조;\">에서 온라인으로도 참여가 가능하며</span></span><span lang=\"EN-US\" style=\"font-size: 12pt;\"><span style=\"letter-spacing: 0pt;\"><span style=\"font-family: 휴먼명조;\">, </span></span></span><span style=\"font-size: 12pt;\"><span style=\"font-family: 휴먼명조;\">유선전화 </span></span><span lang=\"EN-US\" style=\"font-size: 12pt;\"><span style=\"letter-spacing: 0pt;\"><span style=\"font-family: 휴먼명조;\">041-850-0090 </span></span></span><span style=\"font-size: 12pt;\"><span style=\"font-family: 휴먼명조;\">지역협력실로 연락하면 된다</span></span><span lang=\"EN-US\" style=\"font-size: 12pt;\"><span style=\"letter-spacing: 0pt;\"><span style=\"font-family: 휴먼명조;\">.</span></span></span></span></p> \n" +
            "</div>";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        mWebView = findViewById(R.id.webView);
        doWebViewPrint();
    }

    private void doWebViewPrint() {
        // Create a WebView object specifically for printing
        WebView webView = mWebView;

        webView.setWebViewClient(new WebViewClient() {

            public boolean shouldOverrideUrlLoading(WebView view, String url) {
                return false;
            }

            @Override
            public void onPageFinished(WebView view, String url) {
                Log.i(TAG, "page finished loading " + url);
                mWebView = null;
            }
        });

        // Generate an HTML document on the fly:
        String htmlDocument = "<html><body><h1>Test Content</h1><p>Testing, " +
                "testing, testing...</p></body></html>";
        webView.getSettings().setDomStorageEnabled(true);
        webView.loadDataWithBaseURL(null, html, "text/HTML", "UTF-8", null);
//        webView.loadUrl("https://www.kongju.ac.kr/kor/article/hot_news/106625");
    }


}
